@startuml

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

Title Архитектура  состояния системы компании «Будущее 2.0». \n Бизнес разрешил отказаться от легаси-систем и мигрировать на новые сервисы

Person(user, "Бизнес-пользователь", "Бизнес-пользователь компании")
Person(operator, "Оператор", "Оператор клиники")

System_Boundary(b0, "Компания «Будущее 2.0»") {
    Container(webPortal, "Портал самообслуживания", "Web Application", "Портал для создания отчетов и анализа данных")

    System_Boundary(b1, "Техническая реализация Data Mesh") {
      ContainerDb(dlh, "Data Lakehouse", "S3-совместимое хранилище", "Хранилище данных для  данных")
      ContainerDb(dc, "Data Catalog", "Nessie", "Управление метаданными")
      ContainerQueue(queueData, "Слой загрузки данных", "ETL/ELT", "")
    }

    Container(aiServices, "ИИ-сервисы", "Python", "Сервисы для обработки и анализа медицинских данных")
    Container(biServices, "BI-система", "Power BI", "Сервисы для построения отчетов")

    System_Boundary(b2, "Источники данных") {
      Container(fintechServices, "Финансовые сервисы", "Golang/Java", "Сервисы для финансовых операций и обслуживания клиентов")
      Container(innerServices, "Внутренние сервисы", "..", "Сервисы для финансовых операций и обслуживания клиентов")
      Container(eqServices, "Сервисы по работе с оборудованием", "...", "Сервисы компании, которая производит электронику для медицинского оборудования")
      Container(farmServices, "Фармацевтика", "...", "Сервисы фарм-компании")
      Container(clientOp, "Клиентский интерфейс оператора", "...", "Сервисы для работы оператора")
    }
}

Rel(operator, webPortal, "Использует для анализа данных")
Rel(user, webPortal, "Использует для анализа данных")
Rel(webPortal, dc, "Доступ к данным")
Rel(clientOp, dc, "Доступ к данным")
Rel(biServices, dc, "Доступ к медицинским данным")
Rel(dc, dlh, "Доступ к данным")
Rel(aiServices, dc, "Доступ к данным ")
Rel(fintechServices, queueData, "Обработка финансовых данных и предоставление отчетности")
Rel(innerServices, queueData, "Управление клиниками")


Rel(farmServices, queueData, "Фармацевтические данные")
Rel(eqServices, queueData, "Данные о производстве оборудования")
Rel(queueData, dlh, "Данные")
Rel(queueData, dc, "Метаданные")
@enduml